In [2]:
print ("hello")


hello


In [7]:
! pip install pandas

                                              0.0/11.6 MB ? eta -:--:--
                                              0.2/11.6 MB 4.4 MB/s eta 0:00:03
     --                                       0.7/11.6 MB 8.9 MB/s eta 0:00:02
     --                                       0.7/11.6 MB 8.9 MB/s eta 0:00:02
     --                                       0.7/11.6 MB 8.9 MB/s eta 0:00:02
     ----                                     1.3/11.6 MB 6.0 MB/s eta 0:00:02
     -----                                    1.7/11.6 MB 6.5 MB/s eta 0:00:02
     -------                                  2.2/11.6 MB 7.1 MB/s eta 0:00:02
     ---------                                2.6/11.6 MB 7.3 MB/s eta 0:00:02
     ---------                                2.9/11.6 MB 7.1 MB/s eta 0:00:02
     -----------                              3.3/11.6 MB 7.2 MB/s eta 0:00:02
     ------------                             3.6/11.6 MB 7.2 MB/s eta 0:00:02
     -------------                            4.1/11.6 MB 7


[notice] A new release of pip is available: 23.1.2 -> 24.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [8]:
import pandas as pd

In [9]:
Data= pd.read_csv("Advertising.csv",index_col=0)

In [10]:
Data

TV  Radio  Newspaper  Sales
1    230.1   37.8       69.2   22.1
2     44.5   39.3       45.1   10.4
3     17.2   45.9       69.3    9.3
4    151.5   41.3       58.5   18.5
5    180.8   10.8       58.4   12.9
..     ...    ...        ...    ...
196   38.2    3.7       13.8    7.6
197   94.2    4.9        8.1    9.7
198  177.0    9.3        6.4   12.8
199  283.6   42.0       66.2   25.5
200  232.1    8.6        8.7   13.4

[200 rows x 4 columns]

In [12]:
Data.shape

(200, 4)

In [13]:
Data.isnull

<bound method DataFrame.isnull of         TV  Radio  Newspaper  Sales
1    230.1   37.8       69.2   22.1
2     44.5   39.3       45.1   10.4
3     17.2   45.9       69.3    9.3
4    151.5   41.3       58.5   18.5
5    180.8   10.8       58.4   12.9
..     ...    ...        ...    ...
196   38.2    3.7       13.8    7.6
197   94.2    4.9        8.1    9.7
198  177.0    9.3        6.4   12.8
199  283.6   42.0       66.2   25.5
200  232.1    8.6        8.7   13.4

[200 rows x 4 columns]>

In [14]:
x = Data[['TV','Radio','Newspaper']]

In [15]:
y= Data[['Sales']]

In [17]:
! pip install scikit-learn


[notice] A new release of pip is available: 23.1.2 -> 24.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip



                                              0.0/11.0 MB ? eta -:--:--
                                              0.1/11.0 MB 1.7 MB/s eta 0:00:07
                                              0.2/11.0 MB 2.5 MB/s eta 0:00:05
     -                                        0.5/11.0 MB 3.9 MB/s eta 0:00:03
     ---                                      0.9/11.0 MB 4.9 MB/s eta 0:00:03
     ----                                     1.3/11.0 MB 6.0 MB/s eta 0:00:02
     ------                                   1.9/11.0 MB 7.1 MB/s eta 0:00:02
     --------                                 2.4/11.0 MB 7.6 MB/s eta 0:00:02
     --------                                 2.4/11.0 MB 7.6 MB/s eta 0:00:02
     --------                                 2.4/11.0 MB 5.9 MB/s eta 0:00:02
     ------------                             3.6/11.0 MB 7.8 MB/s eta 0:00:01
     --------------                           4.0/11.0 MB 8.1 MB/s eta 0:00:01
     ----------------                         4.6/11.0 MB 

In [18]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size= 0.2)

In [19]:
print(x_train.shape,"Traning data size for x")
print(x_test.shape,"Traning data size for x")
print(y_train.shape,"Traning data size for y")
print(y_test.shape,"Traning data size for y")

(160, 3) Traning data size for x
(40, 3) Traning data size for x
(160, 1) Traning data size for y
(40, 1) Traning data size for y


In [20]:
from sklearn.linear_model import LinearRegression
lm = LinearRegression()
model = lm.fit(x_train,y_train)

In [21]:
model.intercept_

array([2.80894491])

In [22]:
model.coef_

array([[0.04614929, 0.18454379, 0.0038006 ]])

In [26]:
b0 = 2.80894491
b1 = 0.04614929
b2 = 0.18454379
b3 = 0.0038006

y = b0 + b1*44.5 + b2*39.3 + b3*45.1

In [27]:
y

12.286566321999999

In [28]:
y_pred = model.predict(x_test)

In [29]:
y_pred

array([[10.63559194],
       [ 6.54087153],
       [14.05535477],
       [16.28188302],
       [24.7707391 ],
       [ 9.17484976],
       [ 5.99385048],
       [13.64857989],
       [10.3303445 ],
       [ 7.12437762],
       [12.71794997],
       [ 5.72835225],
       [15.37029252],
       [12.28656618],
       [17.16145037],
       [ 8.91120099],
       [15.66160771],
       [14.58069277],
       [13.04289796],
       [21.33253746],
       [16.81665465],
       [ 9.95152117],
       [16.89268067],
       [13.99323726],
       [ 7.4874113 ],
       [18.47433285],
       [ 8.09125727],
       [ 9.66852863],
       [23.24346398],
       [17.17368935],
       [12.01723454],
       [12.04495965],
       [ 4.47944117],
       [18.46883094],
       [13.6834006 ],
       [10.12759784],
       [24.17918664],
       [16.91825218],
       [11.9932051 ],
       [ 7.68548941]])

In [31]:
new_df = pd.DataFrame()
new_df = x_test
new_df['actual sales']= y_test
new_df['predicted sales']= y_pred
new_df

TV  Radio  Newspaper  actual sales  predicted sales
72   109.8   14.3       31.7          12.4        10.635592
23    13.2   15.9       49.6           5.6         6.540872
101  222.4    4.3       49.8          11.7        14.055355
153  197.6   23.3       14.2          16.6        16.281883
176  276.9   48.9       41.8          27.0        24.770739
30    70.6   16.0       40.8          10.5         9.174850
190   18.7   12.1       23.4           6.7         5.993850
123  224.0    2.4       15.6          11.6        13.648580
159   11.7   36.9       45.2           7.3        10.330344
108   90.4    0.3       23.2           8.7         7.124378
198  177.0    9.3        6.4          12.8        12.717950
61    53.5    2.0       21.4           8.1         5.728352
86   193.2   18.4       65.7          15.2        15.370293
2     44.5   39.3       45.1          10.4        12.286566
12   214.7   24.0        4.0          17.4        17.161450
47    89.7    9.9       35.7          10.6         8.911201
26   262.9    3.5       19.5          12.0        15.661608
166  234.5    3.4       84.8          11.9        14.580693
64   102.7   29.6        8.4          14.0        13.042898
56   198.9   49.4       60.0          23.7        21.332537
63   239.3   15.5       27.3          15.7        16.816655
74   129.4    5.7       31.3          11.0         9.951521
90   109.8   47.8       51.4          16.7        16.892681
182  218.5    5.4       27.4          12.2        13.993237
173   19.6   20.1       17.0           7.6         7.487411
15   204.1   32.9       46.0          19.0        18.474333
197   94.2    4.9        8.1           9.7         8.091257
146  140.3    1.9        9.0          10.3         9.668529
148  243.2   49.0       44.3          25.4        23.243464
164  163.5   36.8        7.4          18.0        17.173689
8    120.2   19.6       11.6          13.2        12.017235
149   38.0   40.3       11.9          10.9        12.044960
193   17.2    4.1       31.6           5.9         4.479441
151  280.7   13.9       37.0          16.1        18.468831
78   120.5   28.5       14.2          14.2        13.683401
145   96.2   14.8       38.9          11.4        10.127598
99   289.7   42.3       51.2          25.4        24.179187
100  135.2   41.7       45.9          17.2        16.918252
76    16.9   43.7       89.4           8.7        11.993205
33    97.2    1.5       30.0           9.6         7.685489

In [32]:
from sklearn.metrics import r2_score,mean_squared_error
import numpy as np

r2=r2_score(y_test,y_pred)
print("R-square:",r2)

rmse=np.sqrt(mean_squared_error(y_test,y_pred))
print("RMSE:",rmse)

R-square: 0.895625149497132
RMSE: 1.6918218250912536


In [35]:
car = pd.read_csv("Cars (1).csv",index_col=0)

In [36]:
car

MPG  VOL          SP         WT
HP                                        
49   53.700681   89  104.185353  28.762059
55   50.013401   92  105.461264  30.466833
55   50.013401   92  105.461264  30.193597
70   45.696322   92  113.461264  30.632114
53   50.504232   92  104.461264  29.889149
..         ...  ...         ...        ...
322  36.900000   50  169.598513  16.132947
238  19.197888  115  150.576579  37.923113
263  34.000000   50  151.598513  15.769625
295  19.833733  119  167.944460  39.423099
236  12.101263  107  139.840817  34.948615

[81 rows x 4 columns]

In [37]:
toyota= pd.read_csv("Toyota.csv",index_col=0)

In [38]:
toyota


Price   Age     KM FuelType   HP  MetColor  Automatic    CC  Doors  \
0     13500  23.0  46986   Diesel   90       1.0          0  2000  three   
1     13750  23.0  72937   Diesel   90       1.0          0  2000      3   
2     13950  24.0  41711   Diesel   90       NaN          0  2000      3   
3     14950  26.0  48000   Diesel   90       0.0          0  2000      3   
4     13750  30.0  38500   Diesel   90       0.0          0  2000      3   
...     ...   ...    ...      ...  ...       ...        ...   ...    ...   
1431   7500   NaN  20544   Petrol   86       1.0          0  1300      3   
1432  10845  72.0     ??   Petrol   86       0.0          0  1300      3   
1433   8500   NaN  17016   Petrol   86       0.0          0  1300      3   
1434   7250  70.0     ??      NaN   86       1.0          0  1300      3   
1435   6950  76.0      1   Petrol  110       0.0          0  1600      5   

      Weight  
0       1165  
1       1165  
2       1165  
3       1165  
4       1170  
...      ...  
1431    1025  
1432    1015  
1433    1015  
1434    1015  
1435    1114  

[1436 rows x 10 columns]

In [39]:
toyota.isnull().sum()

Price          0
Age          100
KM             0
FuelType     100
HP             0
MetColor     150
Automatic      0
CC             0
Doors          0
Weight         0
dtype: int64

In [43]:
toyota.describe()

Price          Age     MetColor    Automatic           CC  \
count   1436.000000  1336.000000  1286.000000  1436.000000  1436.000000   
mean   10730.824513    55.672156     0.674961     0.055710  1566.827994   
std     3626.964585    18.589804     0.468572     0.229441   187.182436   
min     4350.000000     1.000000     0.000000     0.000000  1300.000000   
25%     8450.000000    43.000000     0.000000     0.000000  1400.000000   
50%     9900.000000    60.000000     1.000000     0.000000  1600.000000   
75%    11950.000000    70.000000     1.000000     0.000000  1600.000000   
max    32500.000000    80.000000     1.000000     1.000000  2000.000000   

           Weight  
count  1436.00000  
mean   1072.45961  
std      52.64112  
min    1000.00000  
25%    1040.00000  
50%    1070.00000  
75%    1085.00000  
max    1615.00000